config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'homes#top'
  get '/home/about'=> 'homes#about'
  resources :users
  resources :books
  

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
     has_one_attached :image
     belongs_to :user 
     
      validates :title, presence: true
      validates :body, presence: true, length: {maximum:200}
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :books, dependent: :destroy
         
         has_one_attached :profile_image
         
         
         validates :name, uniqueness: true, length:{in: 2..20 }
         validates :introduction, length: {maximum: 50 }
         
         def get_profile_image(width,height)
           unless profile_image.attached?
             file_path=Rails.root.join('app/assets/images/no_image.jpg')
             profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
           end
           profile_image.variant(resize_to_limit:[width,height]).processed
         end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :authenticate_user!, except:[:top,:about]
     before_action :configure_permitted_parameters, if: :devise_controller?
     
     def after_sign_up_path_for(resourse)
         flash[:notice]= "you have successfully completed \(^•^)/"
         user_path(current_user)
     end
     
     def after_sign_in_path_for(resourse)
         flash[:notice]= "you have successfully completed ?"
         user_path(current_user)
     end 
     
     def after_sign_out_path_for(resourse)
         flash[:notice]= "you have successfully good bye!"
         root_path
     end
     
     
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:name,:email])
         
    end 
    
    # def auheniticate_user
        # if current_user==nil
            # redirect_to user_session_path
        # end
    # end
    
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book=Book.new
  end

  def create
    @books=Book.all
    @book_user=current_user
    @book=Book.new(book_params)
    @book.user_id=current_user.id
     if @book.save
       flash[:notice]= "you have successfully completed."
       redirect_to book_path(@book.id)
     else
       render :index
     end 
  end
  
  def show
  @bookuser=Book.find(params[:id])
  @books=Book.all
  @book=Book.new
  @book_user=Book.find(params[:id]).user
  
  end

  def index
    @books =Book.all
    @book=Book.new
    @book_user=current_user
   
  end

  def edit
   @book = Book.find(params[:id])
   if @book.user == current_user
     render :edit
   else
     redirect_to books_path
   end 
   
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice]= "you have successfully completed !"
       redirect_to book_path(@book.id)
    else
      render :edit
    end 
  end 
  
  
private
  
  def book_params
    params.require(:book) .permit(:title,:body)
  end 
  
  
 
  
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_matching_login_user, only: [:edit, :update]

  def edit
    @user =User.find(params[:id])
  end

  def show
    @book=Book.new
    @user= User.find(params[:id])
    @books= @user.books
   
  end
  
  def update
    @user= User.find(params[:id])
     if @user.update(user_params)
        flash[:notice]= "you have successfully completed !?"
        redirect_to user_path
     else
       render :edit
     end 
        
  end 
  
  def index
    @users=User.all
    @book=Book.new
    @book_user=current_user
    
    
  end 
  

  private
  

  
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end 
  
  def is_matching_login_user
  user_id= params[:id].to_i
  unless user_id ==current_user.id
    redirect_to user_path(current_user)
  end 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
                    
                    <h2>User info</h2>
                    
                    <% if user.profile_image.attached? %>
                      <%= image_tag user.profile_image, size:"100x100" %>
                     <%else%>
                      <%= image_tag 'no_image',size:"100x100" %>
                      <%end%>
                     
                       <table class="table">
                           <tbody>
                               <tr></tr>
                               <tr>
                                   <th>name</th>
                                   <th><%= user.name %></th>
                               </tr>
                               <tr>
                                   <th>introdction</th>
                                   <th><%= user.introduction %></th>
                               </tr>
                           </tbody>
                       </table>
                       <div class="row">
                           <%= link_to  edit_user_path(user),class:"btn btn-outline-secondary btn-block" do %>
                           <i class="fas fa-user-cog"></i>
                           <%end%>
                       </div>
                       <h2 class="mt-3">New book</h2>
                       <div>
                           <%= form_with model: book do |f| %>
                           <div class="form-group">
                               <label>Title</label><br/>
                               <%= f.text_field :title, class: "form-control" %>
                               
                               
                           </div>
                           <div class="form-group">
                                <label>Opinion</label><br/>
                                <%= f.text_area :body, class: "form-control" %>
                           </div>
                           <div>
                               <%=f.submit'Create Book',class:"btn btn-success"%>
                           </div>
                                        
                           
                           <%end%>
                           
                       </div>
                     
                </div>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
    
    <body>
        <main>
            <p></p>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
                        <h1>Editing Book</h1>
                        <div class="error_explanation">
                            <% if @book.errors.any? %>
                              <h3>You got <%= @book.errors.count %> error</h3> 
                             <ul>
                              <% @book.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <%end%>
                             </ul>
                            <%end%>
                        </div>
                        
                        <%= form_with model: @book do |f| %>
                        <div class="form-group">
                          <label for="book_title">Title</label><br/>
                          <%= f.text_field :title, class: "form-control book_title" %>
                        </div>
                        <div class="form-group">
                          <label for="book_opinion">Opinion</label><br/>
                          <%= f.text_area :body, class: "form-control book_body" %>
                        </div>
                        <div class="form-group">
                            <%=f.submit'Update Book',class:"btn  btn-success " %>
                        </div>
                            
                        <%end%>
                        <%= link_to "Show", book_path(@book) %>
                        |
                        <a ="back" href="/books">Back</a>
                        
                     
                    </div>
                    
                </div>
            </div>
            
        </main>
    </body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
    <body>
        <p><%= flash[:notice] %></p>
        <div class="container px-5 px-sm-0">
            <div class="error_explanation">
              <% if @book.errors.any? %>
                <h3>You got <%= @book.errors.count %> error</h3> 
               <ul>
                <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <%end%>
               </ul>
              <%end%>
            </div>
            
            <div class="row">

                
                <%= render 'list',  book:@book, user:@book_user %>
                <div class="col-md-8 offset-md-1">
                    <h2>Books</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>Opinion</th>
                                <th colspan="3"></th>
                            </tr>
                        </thead>
                        
                        <% @books.each do |book| %>
                        <% if book.user.profile_image.attached? %>
                        <tr>
                           <td><%= link_to user_path(book.user) do %>
                           <%= image_tag book.user.get_profile_image(80,80) %>
                           <%end%></td>
                            <td><%=link_to  book_path(book) do %>
                            <%= book.title %>
                            <%end%>
                            </td>
                            <td><%= book.body %></td>
                        </tr>
                        <%end%>
                    <%end%>
                     </table>
                </div>
                
                
            </div>
        </div>
        
    </body>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
    <body>
        <p><%= flash[:notice] %></p>
        <div class="container px-5 px-sm-0">
            <div class="row">
            
                <%= render 'list', book:@book, user:@book_user %>
                <div class="col-md-8 offset-md-1">
                    <h2>Book detail</h2>
                    <table class="table">
                        
                        <tbody>
                            <% if @bookuser.user_id==current_user.id %>
                        <tr>
                            
                           <% if @bookuser.user.profile_image.attached? %>
                           <td><%= link_to user_path(@bookuser.user.id) do %>
                            <%= image_tag @bookuser.user.get_profile_image(100,100) %><br/><%= @bookuser.user.name %>
                           <%end%></td>
                            <td><%=link_to  book_path(@bookuser) do %>
                            <%= @bookuser.title %>
                            <%end%></td>
                            <%end%>
                            <td><%= @bookuser.body %></td>
                            <td><%=link_to "Edit", edit_book_path(@bookuser), class:"btn btn-sm btn-success"%></td>
                            <td><%= link_to"Destroy",book_path(@bookuser), method: :delete, "data-confirm" =>"本当に削除しますか？", class:"btn btn-sm btn-danger"%></td>
                        </tr>
                            <%else%>
                        <tr>
                           <% if @bookuser.user.profile_image.attached? %>
                           <td><%= link_to user_path(@bookuser.user.id) do %>
                            <%= image_tag @bookuser.user.get_profile_image(100,100) %><br/><%= @bookuser.user.name %>
                           <%end%></td>
                            <td><%=link_to  book_path(@bookuser) do %>
                            <%= @bookuser.title %>
                            <%end%></td>
                            <%end%>
                            <td><%= @bookuser.body %></td> 
                        </tr>
                            <%end%>
                        
                        
                        </tbody>
                   
                     </table>
                </div>
                
                
            </div>
        </div>
        
    </body>
</html>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
    <body>
        <main>
            <p></p>
             <div class="container">
         <div class="row">
             <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                 <h1>Welcome to <i class="fas fa-book"></i> <strong>Bookers</strong> !</h1>
        </main>
    </body>
    
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>

<html>
   <main>
       <p><%= flash[:notice] %></p>
     <div class="container">
         <div class="row">
             <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                 <h1>welcome to <i class="fas fa-book"></i> <strong>Bookers</strong> !!</h1>
                 <p>in<i class="fas fa-book"></i><strong>bookers</strong>,</p>
                 <p>you can share and exchange your opinions , inpressions , and emotions</p>
                 <p> about various books!</p>
                 
                 <div class="btn-wrapper col-10 mx-auto">
                     <div class="row">
                         <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in" >Log in</a>
                     </div>
                     <div class="row">
                         <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
                     </div>
                 </div>
             </div>
         </div>
     </div>
   </main>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/188eb1a089.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
        
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navgation" >
             <span class="navbar-toggler-icon"></span>
          </button>
        
        <div class="navbar-collapse collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user), class:"nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
              <%end%>
            </li>
            <li>
              <%=link_to users_path, class:"nav-link text-light" do %>
               <i class="fas fa-users"></i> Users
               <%end%>
            </li>
            <li>
              <%= link_to books_path, class:"nav-link text-light" do %>
              <i class="fas fa-book-open"></i> Books
              <%end%>
            </li>
            <li>
               <%= link_to  destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
               <i class="fas fa-sign-out-alt"></i> Log out
               <%end%>
               
            </li>
            
            <%else%>
            
            <li>
              <a class="nav-link text-light" href="/"><i class="fas fa-home"></i> Home</a>
            </li>
            <li>
              <a class="nav-link text-light" href="/home/about"><i class="fas fa-link"></i> About</a>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i> Sign up
              <%end%>
            </li>
            <li>
                <%=link_to  new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i> Log in
                <%end%>
            </li>
            
            <%end%>
          
          </ul>
         </div> 
        </div>
      </nav>
    </header>
    
    
    <main>
      <%= yield %>
    </main>
    
    
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto"><p>CopyRight Infratop.inc</p></div>
        </div>
        <div>
    </footer>
    
    
  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
   
    <p></p>
    <div class="container">
        <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>User info</h2>
            <div class="error_explanation">
                <% if @user.errors.any? %>
                <h3>You got <%= @user.errors.count %> error</h3> 
               <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <%end%>
               </ul>
              <%end%>
            </div>
            <%=form_with model:@user do |f| %>
            <div class="form-group">
                <label for="inputName">Name</label><br/>
                <%= f.text_field :name,autofocus: true, id:"inputName", class: "form-control" %>
            </div>
            <div class="form-group">
                <label for="inputImage">Image</label><br/>
                <%= f.file_field :profile_image, placeholder:"ファイルを選択",accept:"image/*" %>
            </div>
            <div class="form-group">
                <label for="inputIntroduction">Introduction</label><br/>
                <%= f.text_area :introduction, autofocus: true ,id:"inputIntroduction", class: "form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.submit "Update User", class:"btn btn-secondary" %>
            </div>
            <%end%>
        </div>    
        </div>
    </div>
    
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
    <header></header>
    <body>
        <p>users#index</p>
        <div class="container px-5 px-sm-0">
            <div class="row">
                <%= render 'books/list', book:@book, user:@book_user %>
                <div class="col-md-8 offset-md-1">
                    <h2>Users</h2>
                     <table class="table">
                        <thead>
                          <tr>
                             <th>image</th>
                             <th>name</th>
                             <th colspan="3"></th>
                          </tr>
                        </thead>
                        <tbody>
                            <% @users.each do |user| %>
                             <tr> 
                                 <td><%= image_tag user.get_profile_image(80,80) %></td>
                                 <td><%= user.name %></td>
                                 <td><%= link_to "Show", user_path(user) %></td>
                             </tr>
                            <%end%>
                
                        </tbody>
                     </table>
                </div>
                
                
            </div>
        </div>

    </body>
    <footer></footer>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
    <body>
        <p><%= flash[:notice] %></p>
        <div class="container px-5 px-sm-0">
            <div class="row">
                <%= render 'books/list',book:@book, user:@user %>
                <div class="col-md-8 offset-md-1">
                    <h2>Books</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>Opinion</th>
                                <th colspan="3"></th>
                            </tr>
                        </thead>
                        
                            
                        <tbody>
                    <% @books.each do |book| %>
                        <tr>
                           <td><%= link_to user_path(book.user) do %>
                           <%= image_tag @user.get_profile_image(80,80) %>
                           <%end%></td>
                           
                            <td><%=link_to  book_path(book) do %>
                            <%= book.title %>
                            <%end%></td>
                            
                            <td><%= book.body %></td>
                        </tr>
                    <%end%>
                    </tbody>
                     </table>
                </div>
                
                
            </div>
        </div>
        
    </body>
</html>